/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const MessagePlugin: (typeof import('tdesign-vue-next'))['MessagePlugin']
  const TIn: (typeof import('tdesign-vue-next'))['In']
  const TInput: (typeof import('tdesign-vue-next'))['Input']
  const TInut: (typeof import('tdesign-vue-next'))['Inut']
}
